### ISSUE TITLE
Make src publically available due to inactivity

### ISSUE THREAD

**Issue by Miic** [TheDarthFather/AimedHit#2]
Hello, 

It has been over a year since this project has been updated, and I am requesting that you make the src available to the community if you don't have any plans to continue the project so that others can continue updating and adding new features to this and bugfix any current issues.

**Comment by TheDarthFather** [comment]
Unfortunately it seems I lost the src :( ....
Still looking through old backups, but I dont have high hopes.    

Later Edit: 
Found a version. Hopefuly this is helpfull. 
Feel free to add/adjust! Message me if you want to take this over.
My appologises for the long inactivity.
